import './globals.css'
import SideBar from './_components/SideBar'

export const metadata = {
  title: "TaeWoo's Blog",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <SideBar />
          { children }
      </body>
    </html>
  )
}
